# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='emg.proto',
  package='emg',
  serialized_pb='\n\temg.proto\x12\x03\x65mg\"\x89\x01\n\x05\x43hunk\x12\x14\n\x0csubject_name\x18\x01 \x01(\t\x12\x17\n\x0f\x65xperiment_name\x18\x02 \x01(\t\x12$\n\x08readings\x18\x03 \x03(\x0b\x32\x12.emg.Chunk.Reading\x1a+\n\x07Reading\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\r\n\x05value\x18\x02 \x01(\x05')




_CHUNK_READING = _descriptor.Descriptor(
  name='Reading',
  full_name='emg.Chunk.Reading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='emg.Chunk.Reading.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='emg.Chunk.Reading.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=113,
  serialized_end=156,
)

_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='emg.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject_name', full_name='emg.Chunk.subject_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experiment_name', full_name='emg.Chunk.experiment_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='readings', full_name='emg.Chunk.readings', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHUNK_READING, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=156,
)

_CHUNK_READING.containing_type = _CHUNK;
_CHUNK.fields_by_name['readings'].message_type = _CHUNK_READING
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK

class Chunk(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Reading(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CHUNK_READING

    # @@protoc_insertion_point(class_scope:emg.Chunk.Reading)
  DESCRIPTOR = _CHUNK

  # @@protoc_insertion_point(class_scope:emg.Chunk)


# @@protoc_insertion_point(module_scope)
